<script src="${pageContext.request.contextPath}/js/jquery-3.3.1.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/jquery-migrate-3.0.1.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/popper.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/bootstrap.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/owl.carousel.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/jquery.stellar.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/jquery.fancybox.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/aos.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/bootstrap-datepicker.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/jquery.timepicker.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/js/main.js" type="text/javascript"></script>